### ISSUE TITLE
Unable to load shovel definitions at RabbitMQ server start time

### ISSUE THREAD

**Issue by sempasha** [rabbitmq/rabbitmq-shovel#13]
RabbitMQ server with management plugin give an [ability to load server definitions at start time](https://www.rabbitmq.com/management.html#load-definitions). If there are dynamic shovel definition in that file RabbitMQ server failed to start.

In example below I try to create dynamic shovel to move messages from queue `source` to `destination` at local RabbitMQ.

`/etc/rabbitmq/rabbitmq.config` (server configuration)

``` erl
[
    {rabbit, [{loopback_users, []}]},
    {rabbitmq_management, [{load_definitions, "/etc/rabbitmq/definitions.json"}]}
].
```

`/etc/rabbitmq/definitions.json` (queues and shovel declarations)

``` json
{
  "rabbit_version": "3.6.1",
  "users": [
    {
      "name": "guest",
      "password_hash": "YhXgK79L2qYsuPCUEmBRY3np5B3TsfM9u6u+wzDvA0iPMeGh",
      "hashing_algorithm": "rabbit_password_hashing_sha256",
      "tags": "administrator"
    }
  ],
  "vhosts": [
    {
      "name": "/"
    }
  ],
  "permissions": [
    {
      "user": "guest",
      "vhost": "/",
      "configure": ".*",
      "write": ".*",
      "read": ".*"
    }
  ],
  "parameters": [
    {
      "value": {
        "src-uri": "amqp://localhost",
        "src-queue": "source",
        "dest-uri": "amqp://localhost",
        "dest-queue": "destination",
        "add-forward-headers": false,
        "ack-mode": "on-confirm",
        "delete-after": "never"
      },
      "vhost": "/",
      "component": "shovel",
      "name": "test"
    }
  ],
  "policies": [],
  "queues": [
    {
      "name": "source",
      "vhost": "/",
      "durable": true,
      "auto_delete": false,
      "arguments": {}
    },
    {
      "name": "destination",
      "vhost": "/",
      "durable": true,
      "auto_delete": false,
      "arguments": {}
    }
  ],
  "exchanges": [],
  "bindings": []
}
```

RabbitMQ out

```

              RabbitMQ 3.6.1. Copyright (C) 2007-2016 Pivotal Software, Inc.
  ##  ##      Licensed under the MPL.  See http://www.rabbitmq.com/
  ##  ##
  ##########  Logs: tty
  ######  ##        tty
  ##########
              Starting broker...
=INFO REPORT==== 7-Jun-2016::14:04:56 ===
Starting RabbitMQ 3.6.1 on Erlang 18.3
Copyright (C) 2007-2016 Pivotal Software, Inc.
Licensed under the MPL.  See http://www.rabbitmq.com/

=INFO REPORT==== 7-Jun-2016::14:04:56 ===
node           : rabbit@b3b3c483e939
home dir       : /var/lib/rabbitmq
config file(s) : /etc/rabbitmq/rabbitmq.config
cookie hash    : FqA0LwNPytStl0samvHl8Q==
log            : tty
sasl log       : tty
database dir   : /var/lib/rabbitmq/mnesia/rabbit@b3b3c483e939

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Memory limit set to 802MB of 2005MB total.

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Disk free limit set to 50MB

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Limiting to approx 1048476 file handles (943626 sockets)

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
FHC read buffering:  OFF
FHC write buffering: ON

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Database directory at /var/lib/rabbitmq/mnesia/rabbit@b3b3c483e939 is empty. Initialising from scratch...

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Priority queues enabled, real BQ is rabbit_variable_queue

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Management plugin: using rates mode 'basic'

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
msg_store_transient: using rabbit_msg_store_ets_index to provide index

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
msg_store_persistent: using rabbit_msg_store_ets_index to provide index

=WARNING REPORT==== 7-Jun-2016::14:04:58 ===
msg_store_persistent: rebuilding indices from scratch

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Applying definitions from: /etc/rabbitmq/definitions.json

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Creating user 'guest'

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Setting user tags for user 'guest' to [administrator]

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Adding vhost '/'

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Setting permissions for 'guest' in '/' to '.*', '.*', '.*'

=CRASH REPORT==== 7-Jun-2016::14:04:58 ===
  crasher:
    initial call: application_master:init/4
    pid: <0.114.0>
    registered_name: []
    exception exit: {bad_return,
                        {{rabbit,start,[normal,[]]},
                         {'EXIT',
                             {error,
                                 <<"{noproc,{gen_server,call,\n                    [rabbit_shovel_dyn_worker_sup_sup,which_children,\n                     infinity]}}">>}}}}
      in function  application_master:init/4 (application_master.erl, line 134)
    ancestors: [<0.113.0>]
    messages: [{'EXIT',<0.115.0>,normal}]
    links: [<0.113.0>,<0.7.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 188
  neighbours:

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: rabbit
    exited: {bad_return,
                {{rabbit,start,[normal,[]]},
                 {'EXIT',
                     {error,
                         <<"{noproc,{gen_server,call,\n                    [rabbit_shovel_dyn_worker_sup_sup,which_children,\n                     infinity]}}">>}}}}
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: os_mon
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: ranch
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: rabbitmq_web_dispatch
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: webmachine
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: mochiweb
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: syntax_tools
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: ssl
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: public_key
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: crypto
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: mnesia
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: asn1
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: inets
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: amqp_client
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: compiler
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: rabbit_common
    exited: stopped
    type: temporary

=INFO REPORT==== 7-Jun-2016::14:04:58 ===
    application: xmerl
    exited: stopped
    type: temporary


BOOT FAILED
===========

Error description:
   {could_not_start,rabbit,
                    {error,<<"{noproc,{gen_server,call,\n                    [rabbit_shovel_dyn_worker_sup_sup,which_children,\n                     infinity]}}">>}}

Log files (may contain more information):
   tty
   tty


=INFO REPORT==== 7-Jun-2016::14:04:58 ===
Error description:
   {could_not_start,rabbit,
                    {error,<<"{noproc,{gen_server,call,\n                    [rabbit_shovel_dyn_worker_sup_sup,which_children,\n                     infinity]}}">>}}

Log files (may contain more information):
   tty
   tty

{"init terminating in do_boot",{could_not_start,rabbit,{error,<<123,110,111,112,114,111,99,44,123,103,101,110,95,115,101,114,118,101,114,44,99,97,108,108,44,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,91,114,97,98,98,105,116,95,115,104,111,118,101,108,95,100,121,110,95,119,111,114,107,101,114,95,115,117,112,95,115,117,112,44,119,104,105,99,104,95,99,104,105,108,100,114,101,110,44,10,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,105,110,102,105,110,105,116,121,93,125,125>>}}}

Crash dump is being written to: erl_crash.dump...init terminating in do_boot ()
```

**Comment by michaelklishin** [comment]
The problem here is that management starts the import before Shovel is running. Unfortunately we don't know the order in which plugins will start and they should not have ordering inter-dependencies.

You can start a node with a definitions file that does not include the Shovels and then import a separate file that only has shovels.

I'm not sure how we can solve this well, perhaps other than not failing the startup for certain specific cases.

**Comment by michaelklishin** [comment]
To be more correct, "Shovel is not fully initialized", perhaps it *could* be running at that point.

**Comment by sempasha** [comment]
In other words this is issue of management plugin rather than shovel?

**Comment by michaelklishin** [comment]
It's an issue with the interplay between definitions import and Shovel starting concurrently. So if you import definitions without runtime parameters and then only import parameters separately it should work fine.

I'm not sure what a good solution would be without an in-depth investigation.

**Comment by sempasha** [comment]
I come to this issue while building image for docker.
There are only 3 ways to declare users, exchanges, queues and shovels:
   1. [`load_definitions`](https://www.rabbitmq.com/management.html#load-definitions) &mdash; easy way to get server ready to server clients;
   2. rabbitmqclt and rabbitmqadmin (management plugin) &mdash; requires execution of extra commands in container with running Rabbit server;
   3. HTTP API (management plugin) &mdash; need to expose port 15672 to access management API, someone must perform HTTP requests to apply configuration.
In case of 2 and 3 we need extra time to perform CLI calls or HTTP requests, so RabbitMQ server not really ready to be used by clients during this time.

**Comment by michaelklishin** [comment]
4. Split your definitions file into two and apply them in order with a pause in between. HTTP API has a method for definitions upload.

**Comment by sempasha** [comment]
It's better to declare shovels at `rabbitmq.config`, no pause required.
```erl
[
    {rabbit, [
        {loopback_users, []}
    ]},
    {rabbitmq_management, [
        {load_definitions, "/etc/rabbitmq/definitions.json"}
    ]},
    {rabbitmq_shovel, [
        {shovels, [
            {'test', [
                {sources, [
                    {broker, "amqp://"}
                ]},
                {destinations, [
                    {broker, "amqp://"},
                    {declarations, [
                        {'queue.declare', [
                            {queue, <<"destination">>},
                            durable
                        ]}
                    ]}
                ]},
                {queue, <<"source">>},
                {ack_mode, on_confirm},
                {publish_fields, [
                    {exchange, <<"">>},
                    {routing_key, <<"destination">>}
                ]},
                {publish_properties, [
                    {delivery_mode, 2}
                ]},
                {reconnect_delay, 5}
            ]}
        ]}
    ]}
].
```
There is only one thing I worry about in that case. [Basic RabbitMQ image](https://github.com/docker-library/rabbitmq/blob/master/Dockerfile) has an [docker-entrypoint.sh](https://github.com/docker-library/rabbitmq/blob/master/docker-entrypoint.sh) script which can completely rewrite `/etc/rabbitmq/rabbitmq.config` on startup, so all my declarations will be lost.

**Comment by sempasha** [comment]
In my view the key problem "there is no best practice for building preconfigured docker images of RabbitMQ server".

Management plugin with definitions file seems to be the simplest and most usable way to do it, unfortunately this issue does not allow to use this feature.

Might be better to move discussion to [management plugin](https://github.com/rabbitmq/rabbitmq-management) and [docker image](https://github.com/docker-library/rabbitmq) projects.

**Comment by Svechnikov** [comment]
I'm experiencing the same problem. There's a part of the output with the error:

`rabbit_1  | =CRASH REPORT==== 16-May-2017::14:51:44 ===
rabbit_1  |   crasher:
rabbit_1  |     initial call: application_master:init/4
rabbit_1  |     pid: <0.136.0>
rabbit_1  |     registered_name: []
rabbit_1  |     exception exit: {bad_return,
rabbit_1  |                         {{rabbit,start,[normal,[]]},
rabbit_1  |                          {'EXIT',
rabbit_1  |                              {error,
rabbit_1  |                                  <<"{noproc,{gen_server,call,\n                    [rabbit_shovel_dyn_worker_sup_sup,which_children,\n                     infinity]}}">>}}}}
rabbit_1  |       in function  application_master:init/4 (application_master.erl, line 134)
rabbit_1  |     ancestors: [<0.135.0>]
rabbit_1  |     messages: [{'EXIT',<0.137.0>,normal}]
rabbit_1  |     links: [<0.135.0>,<0.31.0>]
rabbit_1  |     dictionary: []
rabbit_1  |     trap_exit: true
rabbit_1  |     status: running
rabbit_1  |     heap_size: 987
rabbit_1  |     stack_size: 27
rabbit_1  |     reductions: 98
rabbit_1  |   neighbours:
rabbit_1  | 
rabbit_1  | =INFO REPORT==== 16-May-2017::14:51:44 ===
rabbit_1  |     application: rabbit
rabbit_1  |     exited: {bad_return,
rabbit_1  |                 {{rabbit,start,[normal,[]]},
rabbit_1  |                  {'EXIT',
rabbit_1  |                      {error,
rabbit_1  |                          <<"{noproc,{gen_server,call,\n                    [rabbit_shovel_dyn_worker_sup_sup,which_children,\n                     infinity]}}">>}}}}
rabbit_1  |     type: temporary`

Are there any news?
Of course, there are some workarounds, but it would be great to have just a single definitions file without having to split it into 2 parts (especially if you use docker).

**Comment by michaelklishin** [comment]
There are no updates. As I explained, this is a fundamental problem with two plugins starting  concurrently. It's not clear how we should approach this since management and Shovel have absolutely no dependencies on each other besides this edge case.

Importing definitions after node start using the HTTP API or importing just the dynamic Shovel definitions side steps this problem entirely.

**Comment by anber500** [comment]
We have been running into this issue as well. Loading shovel configurations in the definitions causes the rabbitmq docker to fail. I had to resort to mounting a separate **shovel-definitions.json** in my docker-compose.yml and then after starting the docker, load the shovel-definitions.json:

 `docker-compose up -d`

`docker exec -it webpay-rabbit rabbitmqadmin import /etc/rabbitmq/shovel-definitions.json`

It works but I would ideally like to get rid of the extra step as it's not very friendly to CI and Dev-opps.
This issue seems happen on all versions of the rabbitmq dockers ☹

**Comment by michaelklishin** [comment]
@sempasha because our tiny team has easily an order of magnitude other things to worry about.

**Comment by michaelklishin** [comment]
Definition import was moved into the core for `3.8.2`. Assuming that we perform it after all plugins were enabled (which I don't think is the case right now), it should address the fundamental problem here. It's a core issue at this point.

**Comment by michaelklishin** [comment]
Addressed https://github.com/rabbitmq/rabbitmq-server/issues/2384.

**Comment by michaelklishin** [comment]
Addressed in https://github.com/rabbitmq/rabbitmq-server/issues/2384 which will ship in `3.8.6`. Those on earlier versions can always [import definitions after node startup](https://www.rabbitmq.com/definitions.html).
