### ISSUE TITLE
Introduce a new custom header containing the timestamp when message was shoveled

### ISSUE THREAD

**Issue by c-datculescu** [rabbitmq/rabbitmq-shovel#2]
Hello.

I would like to propose introducing a new header that should contain the timestamp when message was shovelled. The current headers are already very good in identifying the origin of message among other things, but i think the timestamp would be useful as well.

Thank you,
Cristian.

**Comment by michaelklishin** [comment]
Sounds reasonable, also easy to do.

**Comment by Zteve** [comment]
I suggest the timestamp, if present, should record when the message was *last* shovelled, and include some indication of the shovel that put this there.

Should this feature be an optional feature *of the shovel* (default no timestamp)? I was under the impression that the general assumption was that shovels don't modify the messages they 'shovel' about.

**Comment by c-datculescu** [comment]
Hello.

From the use case i have i think it would be reasonable to make it optional, but i am fine with both options.

Thank you for taking this into consideration.

**Comment by hairyhum** [comment]
Should it be separate header, or maybe it's better be included in `x-shovelled`, since it's already a list of parameters there?

**Comment by michaelklishin** [comment]
including into the existing is fine but will be slightly
more involved to implement in a backwards compatible way. I trust your judgement:)

**Comment by hairyhum** [comment]
New header will be easier to configure (and to implement).
