### ISSUE TITLE
Ensure queues used by Shovel are not left behind

### ISSUE THREAD

**Issue by c-datculescu** [rabbitmq/rabbitmq-shovel#3]
Hello all.

When declaring a shovel, shoveling exchange->exchange, if the destination gets removed, the queue declared by the shovel remains active, piling up messages. Unfortunately, when the target exchange comes back up, a new queue gets established by the shoveling mechanism, and all the messages on the old queue are disappearing along with the queue, leading potentially to message loss.

As an additional question: is it possible to recover the above mentioned messages from the queue and to be redistributed somewhere else? (keeping in mind the queue is exclusive).

Thanks.

**Comment by michaelklishin** [comment]
No, for exclusive queues we can't recover anything by definition. What I think can be improved here is setting a queue TTL to the queues used by Shovel (note that TTL calculated is from the moment the queue is "not used").

**Comment by c-datculescu** [comment]
Hi Michael. I am aware that the exclusive queues are not recoverable from the messages point of view. The solution proposed at least eliminates the nees to manually clean up the queue in such a situation, which is also ok, so that would be useful as well.

Thanks for the answer,
Cristian.

**Comment by michaelklishin** [comment]
The only difficult question is: what TTL value should be used by default?

**Comment by michaelklishin** [comment]
We recently had to revisit a similar TTL value in the MQTT plugin. We ended up setting it to 24 hours.

**Comment by c-datculescu** [comment]
I think 24 hours is a pretty decent value for this particular case. In some rare cases, if the shovel has a lot of traffic might create issues for the accumulating messages, but otherwise it should be fine.

**Comment by hairyhum** [comment]
@c-datculescu are you sure that messages are being collected in source queue? Because if shovel is unable to publish message to destination it crashes shovel worker and connection. So queue is being deleted on every new message, which is not published to destination.

**Comment by c-datculescu** [comment]
Hi.

I will take a look on this, at that point we were left with some internal queues as far as i remember. Will get back once i retested the case.

**Comment by michaelklishin** [comment]
@c-datculescu hi, do you have any updates on this issue?

**Comment by c-datculescu** [comment]
Hi. Sorry for the late reply. I tested again the case that we noticed and i cannot reproduce the behavior that i presented earlier. Might have been something else, but i do remember exclusive queues that looked like `amq.gen--yRaVCBiMJisOyFk7YIHXA`, piling up messages. Can be closed until we maybe manage to reproduce the case.
