### ISSUE TITLE
Forward Proxy Support

### ISSUE THREAD

**Issue by jims1103** [rabbitmq/rabbitmq-shovel#35]
I have a project with dozens of RabbitMQ instances that reside within numerous varied organizations.  These instances route messages around via RabbitMQ Shovels.  The RabbitMQ Shovels are configured to use AMQPS and client certificate authentication with mutual authentication in place.  Some of the instances reside behind firewalls requiring the use of a forward proxy server to communicate out onto the internet.  I am currently unaware of any way to configure RabbitMQ Shovels to utilize a forward proxy.

**Comment by michaelklishin** [comment]
@jims1103 can you please be more specific what exactly are the "forward proxies" in your case? Any TCP level proxy can be used with Shovel connections.

**Comment by michaelklishin** [comment]
OK, so it's forward as in "[the opposite of reverse proxy](https://www.incapsula.com/cdn-guide/glossary/reverse-proxy.html)", or an outbound connection proxy. We need more specifics before any plugin or even protocol extensions can be considered. Please start a rabbitmq-users thread, our team does not use GitHub issues for discussions and half-baked ideas.

Thank you.
