### ISSUE TITLE
Shovel name no longer present in client_properties connection_name (only shows "Shovel")

### ISSUE THREAD

**Issue by dldiehl77** [rabbitmq/rabbitmq-shovel#40]
* RabbitMQ version:  3.7.3
* Erlang version:  20.2.3

When I have a dynamic shovel created and acting as the client on the above versions of RabbitMQ/Erlang and the shovel is connecting to another RabbitMQ server (same versions), the shovel connection shows up in the client_properties connection_name as <<"Shovel">>.  Earlier versions displayed the actual name of the shovel.  So, for example, given a shovel named "my_shovel", the connection_name would appear as <<"Shovel my_shovel">>.

I can demonstrate this by creating a shovel on a version 3.6.10 RabbitMQ server that connects to a version 3.7.3 RabbitMQ server.  In this configuration, the connection_name shows as <<"Shovel my_shovel">>.

I can see these differences in the Management HTTP API in Chrome and also using curl or in Java using Retrofit.

I will repeat below the most relevant parts of what I posted here: https://groups.google.com/forum/#!topic/rabbitmq-users/MSBHD-fRmPM

 -------------------------

I am using dynamic shovels.  My configuration is super-simple.  I created a "testuser" on the 3.7.3 RabbitMQ host and created a durable queue named "a.test.queue".  Then I went to another 3.7.3 RabbitMQ host (the client) and created a shovel with this command and output:

``` bash
rabbitmqctl set_parameter shovel my.test.shovel "{\"src-uri\":\"amqp://testuser:testpwd@shopamqpdev1\", \"src-queue\": \"a.test.queue\", \"dest-uri\": \"amqp://\", \"dest-exchange\":\"a.test.exchange\", \"ack-mode\":\"on-confirm\", \"delete-after\":\"never\"}"
Setting runtime parameter "shovel" for component "my.test.shovel" to "{"src-uri":"amqp://testuser:testpwd@shopamqpdev1", "src-queue": "a.test.queue", "dest-uri": "amqp://", "dest-exchange":"a.test.exchange", "ack-mode":"on-confirm", "delete-after":"never"}" in vhost "/" ...
```

Then I view the connections in the Management API in Chrome and this connection in the first column ("Name") shows up like this:

10.5.130.33:36794
Shovel

Clicking on the link there and drilling into this connection shows the "Client properties" and lists within that the "connection_name".  This shows just the word "Shovel".  The "Details" section also shows a "Client-provided name" and that also shows only the word "Shovel".

However, if my client RabbitMQ server is instead version 3.6.10, then both of these display "Shovel my.test.shovel".

I wasn't sure if this issue has anything to do with what I am seeing or not:  https://github.com/rabbitmq/rabbitmq-server/issues/104

I tried to follow along with the discussion there, but I couldn't really tell what the outcome was.  I pretty much am needing the same feature; do be able to distinguish between multiple connections from the same IP.  If you have an explanation of how I can do that... that is what would solve my dilemma.

**Comment by michaelklishin** [comment]
rabbitmq/rabbitmq-server#104 introduced the concept of user-provided names. #20 made Shovel use them. I don't recall any intentional changes in that area ever since.

**Comment by dldiehl77** [comment]
Regarding #20 the screen snippet clearly shows the shovel name... my_first_shovel

It no longer appears that way when the client connection is 3.7.3.  Am I missing something?  That is not the intended behavior is it?

**Comment by michaelklishin** [comment]
@dldiehl77 no need to state over and over that you don't see the name and you are not sure why. We are not sure either: it wasn't an intentional change. If you would like to investigate it, digging git history for the lines added in #20 is what I'd do first.

**Comment by dldiehl77** [comment]
I looked at the code change that you referred to.  I am not having much luck in understanding it, not knowing Erlang, plus not knowing how this particular source file fits into the overall big picture.  I sure do wish I could have figured it out, though.  I'm going to need to rely on one of you guys to research and fix this when you have time.  Is that acceptable?

**Comment by michaelklishin** [comment]
We will handle it.
