### ISSUE TITLE
Handle AMQP encoded values.

### ISSUE THREAD

**Issue by kjnilsson** [rabbitmq/rabbitmq-shovel#42]
This location can cause a crash when the body of a message is an AMQP 1.0 encoded term (rather than a list of binaries or a list of amqp value sequences).

https://github.com/rabbitmq/rabbitmq-shovel/blob/master/src/rabbit_amqp10_shovel.erl#L180

See mailing list report: https://groups.google.com/forum/#!topic/rabbitmq-users/DhAMhnZmw7A

**Comment by michaelklishin** [comment]
This was fully backported to `3.7.x` in the `3.7.10` cycle.
