### ISSUE TITLE
Shovel reconnection behavior different between 3.7.13 and 3.7.15

### ISSUE THREAD

**Issue by MrKich** [rabbitmq/rabbitmq-shovel#60]
I am using shovels to push messages from local queue to remote exchange.
Shovel connection was restarting endlessly if there is network problem while I used rabbitmq version 3.7.13.
After I upgraded to rabbitmq version 3.7.15 (docker), shovel began to change state to "terminated" and no longer restarts automatically if there is network problems, instead, a button named "Restart" appears.

Rabbitmq docker image: rabbitmq:3.7-management
Enabled plugins:
  - rabbitmq_management
  - rabbitmq_management_agent
  - rabbitmq_web_dispatch
  - rabbitmq_shovel
  - rabbitmq_shovel_management 

Is there a new flag or configuration option to return old behaviour?

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. This assumes that we have a certain amount of information to work with.

Getting all the details necessary to reproduce an issue, make a conclusion or even form a hypothesis about what's happening can take a fair amount of time. Our team is multiple orders of magnitude smaller than the RabbitMQ community. Please help others help you by providing a way to reproduce the behavior you're
observing and sharing as much relevant information as possible [on the list](https://groups.google.com/forum/#!forum/rabbitmq-users):

 * Server, client library and plugin (if applicable) versions used
 * Server logs
 * A code example or terminal transcript that can be used to reproduce
 * **Full** exception stack traces (not a single line message)
 * `rabbitmqctl status` (and, if possible, `rabbitmqctl environment` output)
 * Other relevant things about the environment and workload, e.g. OS/systemd logs, [a traffic capture](https://www.rabbitmq.com/amqp-wireshark.html), deployment tool logs, etc

Feel free to edit out hostnames and other potentially sensitive information.

When/if we have a complete enough understanding of what's going on, a recommendation will be provided or a new issues with more context will be filed.

Thank you.

**Comment by michaelklishin** [comment]
Please provide logs and steps to reproduce (e.g. using Toxiproxy). There aren't any changes in https://github.com/rabbitmq/rabbitmq-shovel/pull/58/files that seem relevant to me.

**Comment by MrKich** [comment]
Okay.

With rabbitmq 3.7.13 shovel looks like [this](https://imgur.com/XnQpd6G) in UI.
With rabbitmq 3.7.15 shovel looks like [this](https://imgur.com/ai1wjUh) in UI. Notice the "Restart" button.

Now I simply block network to shovel destination address by using iptables:
`sudo iptables -I FORWARD 1 -d <ip>/32 -j DROP`

After sometime shovel is trying to [restart](https://imgur.com/MMzWqmj) (1-st and last time)
And after a minute or so shovel is [terminated](https://imgur.com/YLVL7ND) completely and does not restarts.

Output [log](https://pastebin.com/pJQXvt7L) contains:

```
2019-06-06 14:23:41.038 [error] <0.603.0> ** Generic server <0.603.0> terminating 
** Last message in was socket_closed
** When Server state == {state,amqp_network_connection,{state,#Port<0.29>,<<"client 172.17.0.2:55511 -> <removed>:5672">>,10,<0.606.0>,131072,<0.602.0>,undefined,false},<0.605.0>,{amqp_params_network,<<"guest">>,<<"">>,<<"/">>,"<removed>",5672,2047,0,10,60000,none,[#Fun<amqp_uri.12.79294410>,#Fun<amqp_uri.12.79294410>],[{<<"connection_name">>,longstr,<<"Shovel test_shovel">>}],[]},2047,[{<<"capabilities">>,table,[{<<"publisher_confirms">>,bool,true},{<<"exchange_exchange_bindings">>,bool,true},{<<"basic.nack">>,bool,true},{<<"consumer_cancel_notify">>,bool,true},{<<"connection.blocked">>,bool,true},{<<"consumer_priorities">>,bool,true},{<<"authentication_failure_close">>,bool,true},{<<"per_consumer_qos">>,bool,true},{<<"direct_reply_to">>,bool,true}]},{<<"cluster_name">>,longstr,<<"rabbit@<removed>">>},{<<"copyright">>,longstr,<<"Copyright (C) 2007-2019 Pivotal Software, Inc.">>},{<<"information">>,longstr,<<"Licensed under the MPL.  See http://www.rabbitmq.com/">>},{<<"platform">>,longstr,<<"Erlang/OTP 21.2.6">>},{<<"product">>,longstr,<<"RabbitMQ">>},{<<"version">>,longstr,<<"3.7.12">>}],none,false}
** Reason for termination == 
** socket_closed_unexpectedly
2019-06-06 14:23:41.041 [error] <0.603.0> CRASH REPORT Process <0.603.0> with 0 neighbours exited with reason: socket_closed_unexpectedly in gen_server:handle_common_reply/8 line 751
2019-06-06 14:23:41.048 [info] <0.472.0> Shovel 'test_shovel' in virtual host '/' is stopping, reason: {outbound_conn_died,socket_closed_unexpectedly}
2019-06-06 14:23:41.059 [error] <0.601.0> Supervisor {<0.601.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.602.0>, {amqp_params_network,<<"guest">>,<<"">>,<<"/">>,"<removed>",5672,2047,...}) at <0.603.0> exit with reason socket_closed_unexpectedly in context child_terminated
2019-06-06 14:23:41.062 [error] <0.601.0> Supervisor {<0.601.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.602.0>, {amqp_params_network,<<"guest">>,<<"">>,<<"/">>,"<removed>",5672,2047,...}) at <0.603.0> exit with reason reached_max_restart_intensity in context shutdown
2019-06-06 14:23:41.070 [error] <0.472.0> ** Generic server <0.472.0> terminating
** Last message in was {'EXIT',<0.603.0>,socket_closed_unexpectedly}
** When Server state == {state,undefined,undefined,undefined,undefined,{<<"/">>,<<"test_shovel">>},dynamic,#{ack_mode => on_confirm,dest => #{current => {<0.603.0>,<0.612.0>,<<"amqp://<removed>">>},dest_exchange => <<"rse_exchange_in">>,fields_fun => #Fun<rabbit_shovel_parameters.11.64789379>,module => rabbit_amqp091_shovel,props_fun => #Fun<rabbit_shovel_parameters.12.64789379>,resource_decl => #Fun<rabbit_shovel_parameters.10.64789379>,unacked => #{},uris => ["amqp://guest<removed>:@<removed>"]},name => <<"test_shovel">>,reconnect_delay => 10,shovel_type => dynamic,source => #{current => {<0.478.0>,<0.597.0>,<<"amqp://">>},delete_after => never,module => rabbit_amqp091_shovel,prefetch_count => 1000,queue => <<"out_to_upstream">>,remaining => unlimited,remaining_unacked => unlimited,resource_decl => #Fun<rabbit_shovel_parameters.14.64789379>,source_exchange_key => <<>>,uris => ["amqp://"]}},undefined,undefined,undefined,undefined,undefined}
** Reason for termination == 
** {outbound_conn_died,socket_closed_unexpectedly}
2019-06-06 14:23:41.071 [error] <0.472.0> CRASH REPORT Process <0.472.0> with 0 neighbours exited with reason: {outbound_conn_died,socket_closed_unexpectedly} in gen_server2:terminate/3 line 1172
2019-06-06 14:23:41.075 [error] <0.471.0> Supervisor {<0.471.0>,rabbit_shovel_dyn_worker_sup} had child {<<"/">>,<<"test_shovel">>} started with rabbit_shovel_worker:start_link(dynamic, {<<"/">>,<<"test_shovel">>}, [{<<"dest-add-forward-headers">>,true},{<<"dest-add-timestamp-header">>,true},{<<"dest-exchange">>,...},...]) at <0.472.0> exit with reason {outbound_conn_died,socket_closed_unexpectedly} in context child_terminated
2019-06-06 14:24:41.088 [info] <0.771.0> Shovel 'test_shovel' in virtual host '/' is stopping, reason: {timeout,{gen_server,call,[<0.786.0>,connect,60000]}}
```

**Comment by michaelklishin** [comment]
The button is new on 3.7.15. That is expected. Are you saying that in 3.7.13 Shovels never stop restarting but in 3.7.15 they do and that you can consistency reproduce it?

**Comment by michaelklishin** [comment]
How was the Shovel declared?

**Comment by MrKich** [comment]
> How was the Shovel declared?

```
:/# rabbitmqctl list_parameters
Listing runtime parameters for vhost "/" ...
component	name	value
shovel	test_shovel	{"dest-add-forward-headers":true,"dest-add-timestamp-header":true,"dest-exchange":"rse_exchange_in","dest-protocol":"amqp091","dest-uri":"amqp://guest:<removed>@<removed>","reconnect-delay":10,"src-protocol":"amqp091","src-queue":"out_to_upstream","src-uri":"amqp://"}
```

Reconnect-delay was added later and did not helped.

**Comment by michaelklishin** [comment]
So a basic dynamic AMQP 0-9-1 Shovel. That's enough to try to reproduce, thanks.

**Comment by michaelklishin** [comment]
FTR, here's the diff between [v3.7.13 and v3.7.x](https://github.com/rabbitmq/rabbitmq-shovel/compare/v3.7.13...v3.7.x). So far no obviously relevant changes that we could find.

**Comment by MrKich** [comment]
Yep, but it occurs.

Tested version 3.7.14 - shovel restarts endlessly, as needed.

**Comment by lukebakken** [comment]
@michaelklishin -

```
{timeout,{gen_server,call,[<0.786.0>,connect,60000]}}
```

Was an `infinity` changed to `60000` somewhere, not necessarily in this plugin?

**Comment by michaelklishin** [comment]
@lukebakken that happened [2 years ago](https://github.com/rabbitmq/rabbitmq-erlang-client/commit/336f09c60f8c6eaf11c12305e906d62910b1b4c5).

**Comment by MrKich** [comment]
I tried to replace plugin rabbitmq_shovel-3.7.14.ez in docker image of rabbitmq:3.7.14-management
with rabbitmq_shovel-3.7.15.ez from docker image of rabbitmq:3.7-management.
When I turned off network to destination via iptables - shovel terminated after first attempt to restart.

So, it seems that rabbitmq_shovel-3.7.15.ez is the problem one.

**Comment by michaelklishin** [comment]
@MrKich we will try to reproduce, you have provided enough evidence to convince us :)

**Comment by michaelklishin** [comment]
We managed to reproduce this with `master`.

**Comment by michaelklishin** [comment]
Long story short, #54 has affected error handling of Shovels and thus retries. I have a fix ready, it will take a day or two to review.
