### ISSUE TITLE
Store a crypted password in Shovel state, decrypt on access

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-shovel#64]
See https://github.com/rabbitmq/rabbitmq-shovel/issues/62 for background. Erlang's error logger will log the entire process state and in the case of this plugin, it has to keep the password around in order to be able to reconnect.

@lukebakken suggested that we borrow .NET's [`SecureString`](https://docs.microsoft.com/en-us/dotnet/api/system.security.securestring) idea for this case.
The stored value can be encrypted and decrypted on access. This will require support from the Erlang client.

[167149046]

**Comment by michaelklishin** [comment]
I tried a few approaches that clear credentials in the Erlang client and they alone won't be sufficient.
`error_logger` will log Shovel supervisor arguments, so we have to find a way mask them anyway. Most of the work will have to happen in the Erlang client.

**Comment by Esity** [comment]
Thanks @michaelklishin for taking care of this one

**Comment by michaelklishin** [comment]
@Esity our pleasure. @acogoluegnes did most of the work ;) in https://github.com/rabbitmq/rabbitmq-erlang-client/issues/123, which makes most difference to the operator.
