### ISSUE TITLE
Legacy "delete-after" must be checked in rabbit_shovel_dyn_worker_sup.erl

### ISSUE THREAD

**Issue by inikulshin** [rabbitmq/rabbitmq-shovel#72]
It seems like 

`case pget(<<"src-delete-after">>, Config, <<"never">>) of`

in **rabbit_shovel_dyn_worker_sup.erl** must be replaced with 

`case pget(<<"src-delete-after">>, Config, pget(<<"delete-after">>, Config, <<"never">>)) of`

like in **rabbit_shovel_parameters.erl**

**Comment by inikulshin** [comment]
@michaelklishin thanks!

I saw your commit, you did a much better job, than I would do. But, probably, some tests must be duplicate, to test both `src-delete-after` and `delete-after`, if you still support legacy.

> so checking for the previously used key would only affect those who upgrade from versions over 3 years old

It will also affect anyone using old management tools with new RabbitMQ, like our internal scripts, or some old EasyNetQ.ManagementClient for example.

**Comment by michaelklishin** [comment]
There are validation tests that cover both settings. Duplicating all tests sounds like an overkill.
